# Generated by Django 3.0.5 on 2020-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=75, null=True)),
                ('house', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'addresses | Адреса',
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'districts | Районы',
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivingchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'drivingChanges | Изменения в движении',
                'db_table': 'drivingchanges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('deaths', models.IntegerField()),
                ('wounds', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'incident | Происшествия',
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'incidentTypes | Типы происшествий',
                'db_table': 'incidenttypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Influencefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'influenceFactors | Факторы, оказывающие влияние на режим движения',
                'db_table': 'influencefactors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencefactorIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'influencefactors_incidents | Факторы относительно происшествия',
                'db_table': 'influenceFactors_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'lightings | Освещение',
                'db_table': 'lightings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'localities | Населенные пункты',
                'db_table': 'localities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'objects | Объекты УДС',
                'db_table': 'objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectnearIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'objectsNear_incidents | Объекты УДС вблизи места происшествия',
                'db_table': 'objectsnear_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectonIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'objectsOn_incidents | Объекты УДС на месте происшествия',
                'db_table': 'objectson_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'participants_incidents | Участники в происшествии',
                'db_table': 'participants_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'roads |  Дороги',
                'db_table': 'roads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roaddisadvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'roadDisadvantages | Недостатки дорожного покрытия',
                'db_table': 'roaddisadvantages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoaddisadvantageIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'roadDisadvantages_incident | Недостатки дорожного покрытия относительно происшествия',
                'db_table': 'roaddisadvantages_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roadimportance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'roadImportance | Значения дорог',
                'db_table': 'roadimportance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roadwaystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'roadwayStatuses | Состояния проезжей части',
                'db_table': 'roadwaystatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streetcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'streetCategories | Категории улиц',
                'db_table': 'streetcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'subjects | Субъекты',
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'weathers | Погодные условия',
                'db_table': 'weathers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'weathers_incident | Погодные условия для происшествия',
                'db_table': 'weathers_incident',
                'managed': False,
            },
        ),
    ]
