# Generated by Django 3.0.5 on 2020-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentInfluencefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_influenceFactors | Факторы относительно происшествия',
                'db_table': 'incidents_influenceFactors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentObjectnear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_objectsNear | Объекты УДС вблизи места происшествия',
                'db_table': 'incidents_objectsNear',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentObjecton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_objectson | Объекты УДС на месте происшествия',
                'db_table': 'incidents_objectson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_participants | Участники в происшествии',
                'db_table': 'incidents_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentRoaddisadvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_roaddisadvantages | Недостатки дорожного покрытия относительно происшествия',
                'db_table': 'incidents_roaddisadvantages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'incidents_weathers | Погодные условия для происшествия',
                'db_table': 'incidents_weathers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='InfluencefactorIncident',
        ),
        migrations.DeleteModel(
            name='ObjectnearIncident',
        ),
        migrations.DeleteModel(
            name='ObjectonIncident',
        ),
        migrations.DeleteModel(
            name='ParticipantIncident',
        ),
        migrations.DeleteModel(
            name='RoaddisadvantageIncident',
        ),
        migrations.DeleteModel(
            name='WeatherIncident',
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False, 'verbose_name_plural': 'incidents | Происшествия'},
        ),
        migrations.AlterModelTable(
            name='incident',
            table='incidents',
        ),
    ]
