from django.contrib import admin
from .models import *

admin.site.register(Address)
admin.site.register(District)
admin.site.register(Drivingchange)
admin.site.register(Incident)
admin.site.register(Incidenttype)
admin.site.register(Influencefactor)
admin.site.register(IncidentInfluenceFactor)
admin.site.register(Lighting)
admin.site.register(Locality)
admin.site.register(Object)
admin.site.register(IncidentObjectnear)
admin.site.register(IncidentObjecton)
admin.site.register(IncidentParticipant)
admin.site.register(Roaddisadvantage)
admin.site.register(IncidentRoaddisadvantage)
admin.site.register(Roadimportance)
admin.site.register(Road)
admin.site.register(Roadwaystatus)
admin.site.register(Streetcategory)
admin.site.register(Subject)
admin.site.register(Weather)
admin.site.register(IncidentWeather)
