# Generated by Django 3.0.5 on 2020-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consiquence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'consiquences | Последствия',
                'db_table': 'consiquence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.PositiveIntegerField(blank=True, null=True)),
                ('isusedsafetybelt', models.IntegerField(blank=True, db_column='isUsedSafetyBelt', null=True)),
                ('drunkenness', models.IntegerField(blank=True, null=True)),
                ('drivingexperience', models.IntegerField(blank=True, db_column='drivingExperience', null=True)),
            ],
            options={
                'verbose_name_plural': 'participant | Участники',
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'participantActions | Сведения об оставлении места происшествия (участник)',
                'db_table': 'participantactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'participantCategories | Категории участников',
                'db_table': 'participantcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'violations | Нарушения',
                'db_table': 'violations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationassociateParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'violationsassociate_participants | Непосредственные нарушения',
                'db_table': 'violationsassociate_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationimmediateParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'violationsimmediate_participants | Сопутствующие нарушения',
                'db_table': 'violationsimmediate_participants',
                'managed': False,
            },
        ),
    ]
