# Generated by Django 3.0.5 on 2020-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('participant', '0002_auto_20200630_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantViolationassociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'participants_violationsassociate | Непосредственные нарушения',
                'db_table': 'participants_violationsassociate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantViolationimmediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'participants_violationsimmediate | Сопутствующие нарушения',
                'db_table': 'participants_violationsimmediate',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ViolationassociateParticipant',
        ),
        migrations.DeleteModel(
            name='ViolationimmediateParticipant',
        ),
    ]
