# Generated by Django 3.0.5 on 2020-07-02 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('participant', '0003_auto_20200630_2316'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consiquence',
            table='consiquences',
        ),
    ]
