# Generated by Django 3.0.5 on 2020-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=75, null=True)),
                ('house', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'drivetypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivingchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'drivingchanges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('deaths', models.IntegerField()),
                ('wounds', models.IntegerField()),
            ],
            options={
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'incidenttypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Influencefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'influencefactors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencefactorIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'influencefactors_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'lightings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'localities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectnearIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'objectsnear_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectonIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'objectson_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ownershiptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ownershiptypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.PositiveIntegerField(blank=True, null=True)),
                ('isusedsafetybelt', models.IntegerField(blank=True, db_column='isUsedSafetyBelt', null=True)),
                ('drunkenness', models.IntegerField(blank=True, null=True)),
                ('drivingexperience', models.IntegerField(blank=True, db_column='drivingExperience', null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'participantactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participantcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'participantcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'participants_incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roaddisadvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'roaddisadvantages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoaddisadvantageIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'roaddisadvantages_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roadwaystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'roadwaystatuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Streetcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'streetcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Technicalissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=350)),
            ],
            options={
                'db_table': 'technicalissues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalissueTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'technicalissues_transports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_color', models.PositiveIntegerField()),
                ('year', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'transportactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'transporttypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('isadmin', models.IntegerField(db_column='isAdmin')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'violations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationassociateParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'violationsassociate_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationimmediateParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_participant', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'violationsimmediate_participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'weathers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'weathers_incident',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='Drivetypes',
        ),
        migrations.DeleteModel(
            name='Drivingchanges',
        ),
        migrations.DeleteModel(
            name='Incidents',
        ),
        migrations.DeleteModel(
            name='Incidenttypes',
        ),
        migrations.DeleteModel(
            name='Influencefactors',
        ),
        migrations.DeleteModel(
            name='InfluencefactorsIncidents',
        ),
        migrations.DeleteModel(
            name='Lightings',
        ),
        migrations.DeleteModel(
            name='Localities',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.DeleteModel(
            name='Objects',
        ),
        migrations.DeleteModel(
            name='ObjectsnearIncidents',
        ),
        migrations.DeleteModel(
            name='ObjectsonIncidents',
        ),
        migrations.DeleteModel(
            name='Ownershiptypes',
        ),
        migrations.DeleteModel(
            name='Participantactions',
        ),
        migrations.DeleteModel(
            name='Participantcategories',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='ParticipantsIncidents',
        ),
        migrations.DeleteModel(
            name='Roaddisadvantages',
        ),
        migrations.DeleteModel(
            name='RoaddisadvantagesIncident',
        ),
        migrations.DeleteModel(
            name='Roads',
        ),
        migrations.DeleteModel(
            name='Roadwaystatuses',
        ),
        migrations.DeleteModel(
            name='Streetcategories',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Technicalissues',
        ),
        migrations.DeleteModel(
            name='TechnicalissuesTransports',
        ),
        migrations.DeleteModel(
            name='Transportactions',
        ),
        migrations.DeleteModel(
            name='Transports',
        ),
        migrations.DeleteModel(
            name='Transporttypes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Violations',
        ),
        migrations.DeleteModel(
            name='ViolationsassociateParticipants',
        ),
        migrations.DeleteModel(
            name='ViolationsimmediateParticipants',
        ),
        migrations.DeleteModel(
            name='Weathers',
        ),
        migrations.DeleteModel(
            name='WeathersIncident',
        ),
    ]
