# Generated by Django 3.0.5 on 2020-06-29 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0004_auto_20200629_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consiquence',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Participantaction',
        ),
        migrations.DeleteModel(
            name='Participantcategory',
        ),
        migrations.DeleteModel(
            name='Violation',
        ),
        migrations.DeleteModel(
            name='ViolationassociateParticipant',
        ),
        migrations.DeleteModel(
            name='ViolationimmediateParticipant',
        ),
    ]
