# Generated by Django 3.0.5 on 2020-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0006_auto_20200630_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportTechnicalissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'transports_technicalissues | Технические неисправности транспорта',
                'db_table': 'transports_technicalissues',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TechnicalissueTransport',
        ),
    ]
