# Generated by Django 3.0.5 on 2020-09-23 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0007_auto_20200630_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
